---
- name: Make global drush commands dir for islandora
  file:
    path: /usr/local/share/drush/commands/islandora
    state: directory
    recurse: yes

- name: Copy libraries drush defs into global dir
  shell: "cp {{ drupal_core_path }}/sites/all/modules/{{item}} /usr/local/share/drush/commands/islandora/"
  with_items:
    - islandora_openseadragon/islandora_openseadragon.drush.inc
    - islandora_pdfjs/islandora_pdfjs.drush.inc
    - islandora_videojs/islandora_videojs.drush.inc
    - islandora_internet_archive_bookreader/islandora_internet_archive_bookreader.drush.inc

- name: Clear drush cache to register new commands.
  shell: drush cc drush
  args:
    chdir: '{{drupal_core_path}}'

- name: Ensure that videojs library is downloaded and in place.
  shell: "drush -y -v videojs-plugin"
  args:
    chdir: "{{drupal_core_path}}"
    creates: "{{ drupal_core_path }}/sites/all/libraries/video-js"

- name: Ensure that pdf  library is downloaded and in place.
  shell: "drush -y -v pdfjs-plugin"
  args:
    chdir: "{{drupal_core_path}}"
    creates: "{{ drupal_core_path }}/sites/all/libraries/pdfjs"

- name: Ensure that bookreader library is downloaded and in place.
  shell: "drush -y -v iabookreader-plugin"
  args:
    chdir: "{{drupal_core_path}}"
    creates: "{{ drupal_core_path }}/sites/all/libraries/bookreader"

- name: Ensure that seadragon lib is downloaded and in place.
  shell: "drush -y -v openseadragon-plugin"
  args:
    chdir: "{{drupal_core_path}}"
    creates: "{{ drupal_core_path }}/sites/all/libraries/openseadragon"
